name: Build

on:
  push:
    branches: 
      - "**"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/Build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
      - name: Build
        run: cmake --build ${{github.workspace}}/Build --config ${{env.BUILD_TYPE}}
    
      - if: runner.os == 'Windows'
        name: Run
        run: ${{github.workspace}}/Build/Source/Desktop/${{env.BUILD_TYPE}}/Desktop
      
      - if: runner.os != 'Windows'
        name: Run
        run: |
          chmod +x ${{github.workspace}}/Source/Desktop/${{env.BUILD_TYPE}}/Desktop
          ${{github.workspace}}/Source/Desktop/${{env.BUILD_TYPE}}/Desktop
